# source: k16 - http://www.ee.ui.ac.id/web/id/akademik/teknik-komputer-reguler/
# k20 - http://www.ee.ui.ac.id/web/komputer/id/kurikulum/
k16w_tekkom = [     
    'MPKT B',
    'Fisika Listrik, MGO',
    'Prak. Fisika Listrik, MGO',
    'Kalkulus',
    'Dasar Sistem Digital dan Praktikum',
    'MPK Bahasa Inggris',
    'MPKT A',
    'Agama',
    # 'MPK Olahraga/Seni',
    'Aljabar Linier',
    'Fisika Mekanika dan Panas',
    'Prak. Fisika Mekanika dan Panas',
    'Pengantar Teknik Komputer dan Praktikum',
    'Matematika Teknik',
    'Dasar Rangkaian Elektronika',
    'Rangkaian Listrik',
    'Praktikum Rangkaian Listrik dan Elektronik',
    'Organisasi dan Arsitektur Komputer',
    'Struktur Diskrit',
    'Analisis Vektor dan Peubah Kompleks',
    'Pemrograman Lanjut',
    'Sinyal dan Sistem',
    'Perancangan Sistem Digital dan Praktikum',
    # 'Sistem Berbasis Komputer',
    # 'Praktikum Sistem Berbasis Komputer',
    'Jaringan Komputer dan Praktikum',
    'Algoritma',
    'Probabilitas dan Proses Stokastik',
    'Rekayasa Perangkat Lunak',
    'Sistem Embedded 1',
    'Sistem Operasi',
    'Desain & Manajemen Jaringan Komputer + P',
    'Sistem Basis Data dan Praktikum',
    'Jaringan Telekomunikasi',
    'Keamanan Jaringan Komputer dan Praktikum',
    'Sistem Embedded 2 dan Praktikum',
    'Profesionalisme dan Etika dalam Teknologi Informasi',
    'Pemrograman Berorientasi Objek + P',
    # 'Teknologi Nirkabel',
    'Seminar',
    'Kerja Praktek',
    'Kewirausahaan dalam Teknologi Informasi',
    'Kapita Selekta Teknik Komputer',
    # 'Praktikum Jaringan Telekomunikasi',
    # 'Interaksi Manusia dan Komputer',
    'Skripsi',
    'Manajemen Proyek Teknologi Informasi',
    'Pemrosesan Sinyal Multimedia',
    # 'Penulisan Ilmiah'
]

k16p_tekkom = [
    'Dasar Regulasi & Kebijakan Publik TIK',
    'Rekayasa dan Analisis Data',
    'Perancangan VLSI',
    'Teknologi Big Data'
]

# k16h = [
#         'Praktikum Sistem Berbasis Komputer'
#         'Sistem Berbasis Komputer',
#         'Praktikum Jaringan Telekomunikasi',
#         'Penulisan Ilmiah',
#         'Teknologi Nirkabel',
#         'Interaksi Manusia dan Komputer',
#         'Kapita Selekta Teknik Komputer',
#         ]

k16s_tekkom = {
    # Matkul baru : Matkul lama
    # 'MPKT' : 'MPKT A',
    # 'MPKT' : 'MPKT B',
    'Pemrograman Dasar dan Praktikum' : 'Pengantar Teknik Komputer dan Praktikum',
    'Pemrograman Lanjut dan Praktikum' : 'Pemrograman Lanjut',
    'Aljabar Linier Lanjut' : 'Analisis Vektor dan Peubah Kompleks',
    'Sistem Siber-Fisik dan Praktikum' : 'Sistem Embedded 1',
    'Analisis Algoritma' : 'Algoritma',
    'Sistem Waktu Nyata dan IoT dan Praktikum' : 'Sistem Embedded 2 dan Praktikum',
    'Jaringan Telekomunikasi dan Praktikum' : 'Jaringan Telekomunikasi',
    'Teori Sinyal dan Analisis Sistem' : 'Sinyal dan Sistem',
    'Desain Proyek Teknik Komputer 1' : 'Manajemen Proyek Teknologi Informasi',
    'Desain Proyek Teknik Komputer 2' : 'Manajemen Proyek Teknologi Informasi',
    'Pemrograman Berorientasi Objek dan Praktik': 'Pemrograman Berorientasi Objek + P',
    'Profesionalisme dan Etika dalam TI' : 'Profesionalisme dan Etika dalam Teknologi Informasi',
    'Profesionalisme dan Etika dalam Teknologi' : 'Profesionalisme dan Etika dalam Teknologi Informasi',
    'Praktikum Fisika Listrik, MGO' : 'Prak. Fisika Listrik, MGO',
    'Praktikum Fisika Mekanika dan Panas' : 'Prak. Fisika Mekanika dan Panas',
    'Praktikum Fisika Dasar' : 'Prak. Fisika Listrik, MGO',
    'Algoritma Pemrograman dan Praktikum' : 'Pemrograman Lanjut',
    'Matematika Diskrit' : 'Struktur Diskrit',
    'Komputasi Numerik' : 'Algoritma',
    'Matematika Lanjut' : 'Matematika Teknik',
    'Sistem Operasi dan Praktikum' : 'Sistem Operasi',
    'Sistem Embedded dan Praktikum' : 'Sistem Embedded 1',
    'Magang' : 'Kerja Praktek'
}

# k16s_reverse = {
#     # Matkul lama : Matkul baru
#     'MPKT A' : 'MPKT',
#     'MPKT B' : 'MPKT',
#     'Pengantar Teknik Komputer dan Praktikum' : 'Pemrograman Dasar dan Praktikum' ,
#     'Pemrograman Lanjut' : 'Pemrograman Lanjut dan Praktikum',
#     'Analisis Vektor dan Peubah Kompleks' : 'Aljabar Linier Lanjut' ,
#     'Sistem Embedded 1' : 'Sistem Siber-Fisik dan Praktikum' ,
#     'Algoritma' : 'Analisis Algoritma' ,
#     'Sistem Embedded 2 dan Praktikum' : 'Sistem Waktu Nyata dan IoT dan Praktikum' ,
#     'Jaringan Telekomunikasi' : 'Jaringan Telekomunikasi dan Praktikum' ,
#     'Sinyal dan Sistem' : 'Teori Sinyal dan Analisis Sistem',
#     'Manajemen Proyek Teknologi Informasi' : 'Desain Proyek Teknik Komputer 1 DAN 2',
#     # 'Desain Proyek Teknik Komputer 2' : 'Manajemen Proyek Teknologi Informasi',
#     'Pemrograman Berorientasi Objek + P' : 'Pemrograman Berorientasi Objek dan Praktik',
#     'Profesionalisme dan Etika dalam Teknologi Informasi' : 'Profesionalisme dan Etika dalam TI' ,
#     # 'Profesionalisme dan Etika dalam Teknologi' : 'Profesionalisme dan Etika dalam Teknologi Informasi',
#     'Prak. Fisika Listrik, MGO' : 'Praktikum Fisika Listrik, MGO',
#     'Prak. Fisika Mekanika dan Panas' : 'Praktikum Fisika Mekanika dan Panas',    
# }

k20w_tekkom = [
    'Agama',
    'MPK Bahasa Inggris',
    'Kalkulus',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Listrik, MGO',
    'Dasar Sistem Digital dan Praktikum',
    'Pemrograman Dasar dan Praktikum',
    'MPKT',
    'Aljabar Linier',
    'Fisika Mekanika dan Panas',
    'Praktikum Fisika Mekanika dan Panas',
    'Organisasi dan Arsitektur Komputer',
    'Pemrograman Lanjut dan Praktikum',
    'Dasar Rangkaian Elektronika',
    'Jaringan Komputer dan Praktikum',
    'Pemrograman Berorientasi Objek dan Praktik',
    'Perancangan Sistem Digital dan Praktikum',
    'Rangkaian Listrik',
    'Struktur Diskrit',
    'Statistika',
    'Aljabar Linier Lanjut',
    'Analisis Algoritma',
    'Desain & Manajemen Jaringan Komputer + P',
    'Matematika Teknik',
    'Praktikum Rangkaian Listrik dan Elektronik',
    'Sistem Basis Data dan Praktikum',
    'Sistem Operasi',
    'Sistem Siber-Fisik dan Praktikum',
    'Arsitektur Komputer Moderen',
    'Jaringan Telekomunikasi dan Praktikum',
    'Keamanan Jaringan Komputer dan Praktikum',
    'Probabilitas dan Proses Stokastik',
    'Rekayasa Perangkat Lunak',
    'Sistem Waktu Nyata dan IoT dan Praktikum',
    'Teori Sinyal dan Analisis Sistem',
    'Desain Proyek Teknik Komputer 1',
    'Kecerdasan Buatan',
    'Kerja Praktek',
    'Kewirausahaan dalam Teknologi Informasi',
    'Pemrosesan Sinyal Multimedia',
    'Profesionalisme dan Etika dalam Teknologi',
    'Desain Proyek Teknik Komputer 2',
    'Seminar',
    'Skripsi'
]

k20p_tekkom = [
    'Teknologi Big Data',
    'Komputasi Awan',
    'Interaksi Manusia dan Komputer',
    'Teknologi Nirkabel',
    'Teknologi Geospasial',
    'Kapita Selekta Teknik Komputer',
    'Pengembangan Profesional Terpadu - 1',
    # 'Kriptografi',
    'Perancangan VLSI',
    'Berpikir Komputasional',
    'Pengantar Desain Teknik',
    'Dasar Analitik Data',
    'Keberlanjutan, Kesehatan, dan Keselamatan Kerja',
]

# k20s = {
#     #Matkul nama baru : nama lama
#     'MPK Bahasa Inggris' : 'Bahasa Inggris',
#     'Profesionalisme dan Etika dalam Teknologi' : 'Profesionalisme dan Etika dalam Teknologi Informasi',
# }

k20s_tekkom = {
    #Matkul nama baru : nama lama
    'Praktikum Fisika Dasar' : 'Praktikum Fisika Listrik, MGO',
    'Algoritma Pemrograman dan Praktikum' : 'Pemrograman Lanjut dan Praktikum',
    'Matematika Diskrit' : 'Struktur Diskrit',
    'Komputasi Numerik' : 'Analisis Algoritma',
    'Matematika Lanjut' : 'Matematika Teknik',
    'Sistem Operasi dan Praktikum' : 'Sistem Operasi',
    'Sistem Embedded dan Praktikum' : 'Sistem Siber-Fisik dan Praktikum',
    'Magang' : 'Kerja Praktek'
}

k20w_elektro = [
    'Agama',
    'MPK Bahasa Inggris',
    'Kalkulus',
    'Aljabar Linier',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Listrik, MGO',
    'Pengantar Teknik Elektro',
    'MPKT',
    'Fisika Mekanika dan Panas',
    'Praktikum Fisika Mekanika dan Panas',
    'Probabilitas dan Statistika',
    'Rangkaian Listrik 1',
    'Analisis Vektor dan Peubah Kompleks',
    'Dasar Sistem Digital dan Praktikum',
    'Rangkaian Listrik 2',
    'Praktikum Rangkaian Listrik',
    'Matematika Teknik',
    'Fisika Semikonduktor',
    'Aljabar Linear Lanjut',
    'Elektromagnetika',
    'Pengukuran Besaran Listrik',
    'Praktikum Pengukuran Besaran Listrik',
    'Dasar Komputer dan Praktikum',
    'Rangkaian Elektronika 1',
    'Praktikum Rangkaian Elektronika',
    'Sinyal dan Sistem',
    'Teknik Tenaga Listrik',
    'Praktikum Teknik Tenaga Listrik',
    'Komputasi Numerik',
    'Material Listrik',
    'Sistem Benam 1',
    'Algoritma dan Pemrograman',
    'Pengantar Sistem Telekomunikasi',
    'Praktikum Sistem Telekomunikasi',
    'Rangkaian Elektronika 2',
    'Teknik Kendali',
    'Praktikum Teknik Kendali',
    'Sistem Benam 2',
    'Praktikum Sistem Benam',
    'Pemodelan dan Pembelajaran Mesin',
    'Inovasi dan Kewirausahaan',
    'K3LL',
    'Desain Proyek Teknik Elektro 1',
    'Kerja Praktek',
    'Desain Proyek Teknik Elektro 2',
    'Pra-Skripsi',
    'Skripsi'
]

k20m_elektronika = [
    'Desain Rangkaian Elektronika',
    'Divais Elektronika Lanjut',
    'Desain Instrumentasi Elektronika',
    'Divais Optoelektronik',
    'Desain Rangkaian VLSI',
    'Pengantar Nanoelektronika',
    'Topik Khusus Elektronika 1',
    'Sistem Benam Lanjut',
    'Topik Khusus Elektronika 2'
]

k20m_listrik = [
    'Elektronika Daya dan Praktikum',
    'Konversi Energi Listrik dan Energi Baru Terbarukan',
    # 'Manajemen dan Ekonomi Teknik',
    'Sistem Tenaga Listrik dan Praktikum',
    'Teknik Tegangan dan Arus Tinggi dan Praktikum',
    'Topik Khusus Tenaga Listrik 1',
    'Jaringan Cerdas',
    'Instalasi Listrik Bangunan',
    'Proteksi Sistem Tenaga Listrik',
    'Topik Khusus Tenaga Listrik 2'
]

k20m_telkom = [
    'Komunikasi Digital',
    'Divais Sistem Telekomunikasi',
    'Komunikasi Optik',
    'Antena dan Propagasi',
    'Komunikasi Nirkabel dan Jaringan Konvergensi',
    'Kapita Selekta Ekosistem Telekomunikasi',
    'Topik Khusus Telekomunikasi 1',
    'Pengolahan Sinyal dan Layanan Multimedia',
    'Topik Khusus Telekomunikasi 2'
]

k20m_kendali = [
    'Sistem Kendali Motor Listrik',
    'Sistem Kendali Prediktif dan Adaptif',
    'Sistem Otomasi Industri',
    'Sistem Kendaraan Otonomus',
    'Sistem Berbasis Pengetahuan',
    'Sistem Robotika',
    'Topik Khusus Kendali 1',
    'Mekatronika',
    'Topik Khusus Kendali 2'
]

k20p_elektro = [
    # 'Topik Khusus Tenaga Listrik 1',
    # 'Topik Khusus Telekomunikasi 1',
    # 'Topik Khusus Elektronika 1',
    # 'Topik Khusus Kendali 1',
    # 'Topik Khusus Tenaga Listrik 2',
    # 'Topik Khusus Telekomunikasi 2',
    # 'Topik Khusus Elektronika 2',
    # 'Topik Khusus Kendali 2'
]

k20s_elektro = {
    #Matkul nama baru : nama lama
    'Pengantar Desain Teknik' : 'Pengantar Teknik Elektro',
    'Matematika Lanjut 2' : 'Matematika Teknik',
    'Praktikum Fisika Dasar' : 'Praktikum Fisika Listrik, Magnet, Gelombang, Optik',
    'Statistik dan Probabilitas' : 'Probabilitas dan Statistik',
    'Matematika Lanjut 1' : 'Aljabar Linear Lanjut',
    'Devais Semikonduktor' : 'Fisika Semikonduktor',
    'Elektromagnetika' : 'Elektromagnetika',
    'Instrumentasi dan Pengukuran' : 'Pengukuran Besaran Listrik',
    'Praktikum Instrumentasi dan Pengukuran' : 'Praktikum Pengukuran Besaran  Listrik',
    'Berpikir Komputasional' : 'Dasar Komputer dan Praktikum',
    'Sistem Embedded 1' : 'Sistem Benam 1',
    'Algoritma dan Pemrograman dan Praktikum' : 'Algoritma dan Pemrograman',
    'Sistem Telekomunikasi' : 'Pengantar Sistem Telekomunikasi',
    'Sistem Embedded 2 dan Praktikum' : 'Sistem Benam 2',
    'Keberlanjutan, Kesehatan dan Keselamatan Kerja' : 'K3LL',
    'Magang' : 'Kerja Praktek',
    'Seminar' : 'Pra-Skripsi',
    'Desain Ekosistem TIK' : 'Kapita Selekta Ekosistem Telekomunikasi',
    'Devais Nanoelektronika' : 'Pengantar Nanoelektronika',
    'Rangkaian Mikroelektronika' : 'Desain Rangkaian Elektronika',
    'Jaringan Listrik Cerdas' : 'Jaringan Cerdas',
    'Distribusi dan Instalasi Listrik' : 'Instalasi Listrik Bangunan',
    'Sistem Embedded Lanjut' : 'Sistem Benam Lanjut',
    'Devais Elektronika Lanjut' : 'Divais Elektronika Lanjut',
    'Devais Optoelektronik' : 'Divais Optoelektronik',
    'Devais Sistem Telekomunikasi' : 'Divais Sistem Telekomunikasi'
}

k20w_biomed = [
    'MPK Bahasa Inggris',
    'Agama',
    'Kalkulus',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Listrik, MGO',
    'Kimia Dasar',
    'Biologi Teknik dan Praktikum',
    'Dasar Sistem Digital dan Praktikum',
    'MPKT',
    'Aljabar Linier',
    'Fisika Mekanika dan Panas',
    'Praktikum Fisika Mekanika dan Panas',
    'Praktikum Kimia Dasar',
    'Menggambar Teknik',
    'Pengantar Informatika Medis',
    'Matematika Teknik 1',
    'Statistik dan Probabilitas Biomedik',
    'Elektronika Analog',
    'Praktikum Elektronika Analog',
    'Dasar Anatomi dan Fisiologi',
    'Pengantar Teknologi Biomedik',
    'Rangkaian Listrik',
    'Etika Teknologi Biomedik',
    'Matematika Teknik 2',
    'Dasar Komputer dan Praktikum',
    'Sinyal dan Sistem',
    'Pengantar Instrumentasi Biomedik',
    'Pemodelan Sistem Medis',
    'Praktikum Pengantar Teknologi Biomedik',
    'Teori Medan Elektromagnetika',
    'Teknologi Pencitraan Medis',
    'Biomekanika',
    'Biomaterial',
    'Dasar Sistem Otomasi Biomedik',
    'Divais Medis Sistem RF dan Microwave',
    'Komputasi Numerik',
    'Pengolahan Sinyal Medis',
    'Perancangan Sensor Biomedik',
    'Standar Regulasi Teknik Biomedik',
    'Desain Proyek Teknik Biomedik 1',
    'Kerja Praktek',
    'Desain Proyek Teknik Biomedik 2',
    'Pra-Skripsi',
    'Skripsi'
]

k20p_biomed = [
    'Topik Khusus Biomedik 1',
    'Sistem Komunikasi Medis',
    'Topik Khusus Biomedik 2',
    'Proyek Penelitian Teknik Biomedik',
    'Kecerdasan Buatan Biomedik',
    'Rekayasa Biologi Molekuler',
    'Rekayasa Imunologi',
    'Teknologi Kedokteran Regeneratif',
    'Teknik Perumahsakitan',
    'Komputasi Biologi dan Bioinformatika ',
    'Rekayasa Sistem Saraf',
    'Robotika Medis',
    'Teknologi Kedokteran Onkologi',
    'Teknik Rehabilitasi'
]

k20s_biomed = {
    #Matkul nama baru : nama lama
    'Biologi Dasar dan Praktikum' : 'Biologi Teknik dan Praktikum',
    'Matematika Lanjut 1' : 'Matematika Teknik 1',
    'Statistik dan Probabilitas' : 'Statistik dan Probabilitas Biomedik',
    'Anatomi dan Fisiologi Biomedik' : 'Dasar Anatomi dan Fisiologi',
    'Profesionalisme, Etika, dan Kewirausahaan Teknik Biomedik' : 'Etika Teknologi Biomedik',
    'Matematika Lanjut 2' : 'Matematika Teknik 2',
    'Praktikum Pemrograman C' : 'Dasar Komputer dan Praktikum',
    'Sinyal dan Sistem Biomedik' : 'Sinyal dan Sistem',
    # 'Manajemen Alat Kesehatan' : 'Pengantar Instrumentasi Biomedik',
    # 'Manajemen Alat Kesehatan' : 'Standar Regulasi Teknik Biomedik',
    'Pemodelan Sistem Biomedik' : 'Pemodelan Sistem Medis',
    # 'Elektromagnetika dan Perancangan Divais RF Medis' : 'Teori Medan Elektromagnetika',
    # 'Elektromagnetika dan Perancangan Divais RF Medis' : 'Divais Medis Sistem RF dan Microwave',
    'Otomasi dan Kendali Sistem Biomedik' : 'Dasar Sistem Otomasi Biomedik',
    'Komputasi Numerik Biomedik' : 'Komputasi Numerik',
    'Magang' : 'Kerja Praktek',
    'Seminar' : 'Pra-Skripsi'
}

# sks20 = {
#     'Agama' : 2,
#     'Bahasa Inggris' : 2,
#     'Kalkulus' : 3,
#     'Fisika Listrik, MGO' : 3,
#     'Pemrograman Dasar dan Praktikum' : 3,
#     'Dasar Sistem Digital dan Praktikum' : 3,
#     'MPKT' : 5,
#     'Aljabar Linier' : 4,
#     'Fisika Mekanika dan Panas' : 3,
#     'Praktikum Fisika Mekanika dan Panas' : 1,
#     'Organisasi dan Arsitektur Komputer' : 3,
#     'Pemrograman Lanjut dan Praktikum' : 3,
#     'Pemrograman Berorientasi Objek dan Praktik' : 3,
#     'Dasar Rangkaian Elektronika' : 2,
#     'Rangkaian Listrik' : 2,
#     'Statistika' : 3,
#     'Aljabar Linier Lanjut' : 2,
#     'Sistem Siber-Fisik dan Praktikum' : 3,
#     'Analisis Algoritma' : 3,
#     'Sistem Operasi' : 2 ,
#     'Desain & Manajemen Jaringan Komputer + P' : 4,
#     'Sistem Basis Data dan Praktikum' : 3,
#     'Matematika Teknik' : 4,
#     'Praktikum Rangkaian Listrik dan Elektronik' : 1,
#     'Rekayasa Perangkat Lunak' : 3,
#     'Sistem Waktu Nyata dan IoT dan Praktikum' : 3,
#     'Keamanan Jaringan Komputer dan Praktikum' : 3,
#     'Jaringan Telekomunikasi dan Praktikum' : 3,
#     'Arsitektur Komputer Moderen' : 2,
#     'Probabilitas dan Proses Stokastik' : 2,
#     'Teori Sinyal dan Analisis Sistem' : 2,
#     'Desain Proyek Teknik Komputer 1' : 2,
#     'Pemrosesan Sinyal Multimedia' : 3,
#     'Kecerdasan Buatan' : 3,
#     'Kerja Praktek' : 2,
#     'Kewirausahaan dalam Teknologi Informasi' : 2,
#     'Profesionalisme dan Etika dalam Teknologi Informasi' : 2,
#     'Desain Proyek Teknik Komputer 2' : 3,
#     'Seminar' : 2,
#     'Skripsi' : 4
# }

k24w_tekkom = [
    'Agama',
    'MPK Bahasa Inggris',
    'Kalkulus',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Dasar',
    'Dasar Sistem Digital dan Praktikum',
    'Pemrograman Dasar dan Praktikum',
    'Berpikir Komputasional',
    'MPKT',
    'Aljabar Linier',
    'Fisika Mekanika dan Panas',
    'Organisasi dan Arsitektur Komputer',
    'Algoritma Pemrograman dan Praktikum',
    'Pengantar Desain Teknik',
    'Dasar Rangkaian Elektronika',
    'Jaringan Komputer dan Praktikum',
    'Pemrograman Berorientasi Objek dan Praktik',
    'Perancangan Sistem Digital dan Praktikum',
    'Rangkaian Listrik',
    'Matematika Diskrit',
    'Statistika',
    'Aljabar Linier Lanjut',
    'Komputasi Numerik',
    'Desain & Manajemen Jaringan Komputer + P',
    'Matematika Lanjut',
    'Praktikum Rangkaian Listrik dan Elektronik',
    'Sistem Basis Data dan Praktikum',
    'Sistem Operasi dan Praktikum',
    'Sistem Embedded dan Praktikum',
    'Dasar Analitik Data',
    'Arsitektur Komputer Moderen',
    'Jaringan Telekomunikasi dan Praktikum',
    'Keamanan Jaringan Komputer dan Praktikum',
    'Probabilitas dan Proses Stokastik',
    'Rekayasa Perangkat Lunak',
    'Sistem Waktu Nyata dan IoT dan Praktikum',
    'Teori Sinyal dan Analisis Sistem',
    'Desain Proyek Teknik Komputer 1',
    'Kecerdasan Buatan',
    'Magang',
    'Kewirausahaan dalam Teknologi Informasi',
    'Pemrosesan Sinyal Multimedia',
    'Profesionalisme dan Etika dalam Teknologi',
    'Keberlanjutan, Kesehatan, dan Keselamatan Kerja',
    'Komputasi Awan',
    'Interaksi Manusia dan Komputer',
    'Desain Proyek Teknik Komputer 2',
    'Seminar',
    'Skripsi'
]

k24p_tekkom = [
    'Teknologi Big Data',
    'Teknologi Nirkabel',
    'Teknologi Geospasial',
    'Kapita Selekta Teknik Komputer',
    'Pengembangan Profesional Terpadu - 1',
    'Perancangan VLSI'
]

k24s_tekkom = {
    #Matkul nama lama : nama baru
    'Praktikum Fisika Listrik, MGO' : 'Praktikum Fisika Dasar',
    'Pemrograman Lanjut dan Praktikum' : 'Algoritma Pemrograman dan Praktikum',
    'Struktur Diskrit' : 'Matematika Diskrit',
    'Analisis Algoritma' : 'Komputasi Numerik',
    'Matematika Teknik' : 'Matematika Lanjut',
    'Sistem Operasi' : 'Sistem Operasi dan Praktikum',
    'Sistem Siber-Fisik dan Praktikum' : 'Sistem Embedded dan Praktikum',
    'Kerja Praktek' : 'Magang',
    'MPKT A' : 'MPKT',
    'MPKT B' : 'MPKT',
    'Pengantar Teknik Komputer dan Praktikum' : 'Pemrograman Dasar dan Praktikum' ,
    'Pemrograman Lanjut' : 'Algoritma Pemrograman dan Praktikum',
    'Analisis Vektor dan Peubah Kompleks' : 'Aljabar Linier Lanjut',
    'Sistem Embedded 1' : 'Sistem Embedded dan Praktikum',
    'Algoritma' : 'Komputasi Numerik',
    'Sistem Embedded 2 dan Praktikum' : 'Sistem Waktu Nyata dan IoT dan Praktikum',
    'Jaringan Telekomunikasi' : 'Jaringan Telekomunikasi dan Praktikum',
    'Sinyal dan Sistem' : 'Teori Sinyal dan Analisis Sistem',
    'Manajemen Proyek Teknologi Informasi' : 'Desain Proyek Teknik Komputer 1 DAN 2',
    # 'Desain Proyek Teknik Komputer 2' : 'Manajemen Proyek Teknologi Informasi',
    'Pemrograman Berorientasi Objek + P' : 'Pemrograman Berorientasi Objek dan Praktik',
    'Profesionalisme dan Etika dalam Teknologi Informasi' : 'Profesionalisme dan Etika dalam TI' ,
    # 'Profesionalisme dan Etika dalam Teknologi' : 'Profesionalisme dan Etika dalam Teknologi Informasi',
    'Prak. Fisika Listrik, MGO' : 'Praktikum Fisika Dasar',
    'Prak. Fisika Mekanika dan Panas' : 'Praktikum Fisika Mekanika dan Panas'
}

k24w_elektro = [
    'Agama',
    'MPK Bahasa Inggris',
    'Kalkulus',
    'Aljabar Linier',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Dasar',
    'Pengantar Desain Teknik',
    'MPK Terintegrasi ',
    'Fisika Mekanika dan Panas',
    'Statistik dan Probabilitas',
    'Rangkaian Listrik 1',
    'Analisis Vektor dan Peubah Kompleks',
    'Dasar Sistem Digital dan Praktikum',
    'Rangkaian Listrik 2',
    'Praktikum Rangkaian Listrik ',
    'Matematika Lanjut 2',
    'Devais Semikonduktor',
    'Matematika Lanjut 1',
    'Elektromagnetika',
    'Instrumentasi dan Pengukuran',
    'Praktikum Instrumentasi dan Pengukuran',
    'Berpikir Komputasional',
    'Dasar Analitik Data',
    'Matematika Diskrit',
    'Rangkaian Elektronika 1',
    'Praktikum Rangkaian Elektronika',
    'Sinyal dan Sistem',
    'Teknik Tenaga Listrik',
    'Praktikum Teknik Tenaga Listrik',
    'Komputasi Numerik',
    'Material Listrik',
    'Sistem Embedded 1',
    'Algoritma Pemrograman dan Praktikum',
    'Sistem Telekomunikasi',
    'Praktikum Sistem Telekomunikasi',
    'Rangkaian Elektronika 2',
    'Teknik Kendali',
    'Praktikum Teknik Kendali',
    'Sistem Embedded 2 dan Praktikum',
    'Pemodelan dan Pembelajaran Mesin',
    'Inovasi dan Kewirausahaan',
    'Keberlanjutan, Kesehatan dan Keselamatan Kerja',
    'Desain Proyek Teknik Elektro 1',
    'Magang',
    'Desain Proyek Teknik Elektro 2',
    'Seminar',
    'Skripsi'
]

k24m_elektronika = [
    'Rangkaian Elektronika',
    'Devais Elektronika Lanjut',
    'Desain Instrumentasi Elektronika',
    'Devais Optoelektronik',
    'Desain Rangkaian VLSI',
    'Devais Nanoelektronika',
    'Sistem Embedded Lanjut'
]

k24m_listrik = [
    'Elektronika Daya dan Praktikum',
    'Konversi Energi Listrik dan Energi Baru Terbarukan',
    'Sistem Tenaga Listrik dan Praktikum',
    'Teknik Tegangan dan Arus Tinggi dan Praktikum',
    'Jaringan Listrik Cerdas',
    'Distribusi dan Instalasi Listrik',
    'Proteksi Sistem Tenaga Listrik'
]

k24m_telkom = [
    'Komunikasi Digital',
    'Devais Sistem Telekomunikasi',
    'Komunikasi Optik',
    'Antena dan Propagasi',
    'Komunikasi Nirkabel dan Jaringan Konvergensi',
    'Desain Ekosistem TIK',
    'Pengolahan Sinyal dan Layanan Multimedia',
    'Sistem Radar'
]

k24m_kendali = [
    'Sistem Kendali Motor Listrik',
    'Sistem Kendali Prediktif dan Adaptif',
    'Sistem Otomasi Industri',
    'Sistem Kendaraan Otonomus',
    'Sistem berbasis Pengetahuan',
    'Sistem Robotika',
    'Mekatronika'
]

k24p_elektro = [
    'Topik Khusus Tenaga Listrik 1',
    'Topik Khusus Telekomunikasi 1',
    'Topik Khusus Elektronika 1',
    'Topik Khusus Kendali 1',
    'Topik Khusus Tenaga Listrik 2',
    'Topik Khusus Telekomunikasi 2',
    'Topik Khusus Elektronika 2',
    'Topik Khusus Kendali 2'
]

k24s_elektro = {
    #Matkul nama lama : nama baru
    'Pengantar Teknik Elektro' : 'Pengantar Desain Teknik',
    'Matematika Teknik' : 'Matematika Lanjut 2',
    'Praktikum Fisika Listrik, Magnet, Gelombang, Optik' : 'Praktikum Fisika Dasar',
    'Probabilitas dan Statistik' : 'Statistik dan Probabilitas',
    'Aljabar Linear Lanjut' : 'Matematika Lanjut 1',
    'Fisika Semikonduktor' : 'Devais Semikonduktor',
    'Elektromagnetika' : 'Elektromagnetika',
    'Pengukuran Besaran Listrik' : 'Instrumentasi dan Pengukuran',
    'Praktikum Pengukuran Besaran  Listrik' : 'Praktikum Instrumentasi dan Pengukuran',
    'Dasar Komputer dan Praktikum' : 'Berpikir Komputasional',
    'Sistem Benam 1' : 'Sistem Embedded 1',
    'Algoritma dan Pemrograman' : 'Algoritma dan Pemrograman dan Praktikum',
    'Pengantar Sistem Telekomunikasi' : 'Sistem Telekomunikasi',
    'Sistem Benam 2' : 'Sistem Embedded 2 dan Praktikum',
    'K3LL' : 'Keberlanjutan, Kesehatan dan Keselamatan Kerja',
    'Kerja Praktek' : 'Magang',
    'Pra-Skripsi' : 'Seminar',
    'Kapita Selekta Ekosistem Telekomunikasi' : 'Desain Ekosistem TIK',
    'Pengantar Nanoelektronika' : 'Devais Nanoelektronika',
    'Desain Rangkaian Elektronika' : 'Rangkaian Mikroelektronika',
    'Jaringan Cerdas' : 'Jaringan Listrik Cerdas',
    'Instalasi Listrik Bangunan' : 'Distribusi dan Instalasi Listrik',
    'Sistem Benam Lanjut' : 'Sistem Embedded Lanjut',
    'Divais Elektronika Lanjut' : 'Devais Elektronika Lanjut',
    'Divais Optoelektronik' : 'Devais Optoelektronik',
    'Divais Sistem Telekomunikasi' : 'Devais Sistem Telekomunikasi'
}

k24w_biomed = [
    'MPK Bahasa Inggris',
    'Agama',
    'Kalkulus',
    'Fisika Listrik, MGO',
    'Praktikum Fisika Listrik, MGO',
    'Kimia Dasar',
    'Biologi Dasar dan Praktikum',
    'Pengantar Desain Teknik',
    'Praktikum Kimia Dasar',
    'Dasar Sistem Digital dan Praktikum',
    'MPKT',
    'Aljabar Linier',
    'Fisika Mekanika dan Panas',
    'Praktikum Fisika Mekanika dan Panas',
    'Rangkaian Listrik',
    'Pengantar Informatika Medis',
    'Matematika Lanjut 1',
    'Statistik dan Probabilitas',
    'Elektronika Analog',
    'Praktikum Elektronika Analog',
    'Anatomi dan Fisiologi Biomedik',
    'Pengantar Teknologi Biomedik',
    'Berpikir Komputasional',
    'Menggambar Teknik',
    'Matematika Lanjut 2',
    'Praktikum Pemrograman C',
    'Sinyal dan Sistem Biomedik',
    'Manajemen Alat Kesehatan',
    'Pemodelan Sistem Biomedik',
    'Praktikum Pengantar Teknologi Biomedik',
    'Dasar Analitik Data',
    'Komputasi Numerik Biomedik',
    'Teknologi Pencitraan Medis',
    'Biomekanika',
    'Biomaterial',
    'Otomasi dan Kendali Sistem Biomedik',
    'Keberlanjutan, Kesehatan dan Keselamatan Kerja',
    'Sistem Embedded Biomedik dan Praktikum',
    'Profesionalisme, Etika, dan Kewirausahaan Teknik Biomedik',
    'Elektromagnetika dan Perancangan Divais RF Medis',
    'Pengolahan Sinyal Medis',
    'Perancangan Sensor Biomedik',
    'Desain Proyek Teknik Biomedik 1',
    'Magang',
    'Desain Proyek Teknik Biomedik 2',
    'Seminar',
    'Skripsi'
]

k24p_biomed = [
    'Topik Khusus Biomedik 1',
    'Sistem Komunikasi Medis',
    'Topik Khusus Biomedik 2',
    'Proyek Penelitian Teknik Biomedik',
    'Kecerdasan Buatan Biomedik',
    'Rekayasa Biologi Molekuler',
    'Rekayasa Imunologi',
    'Teknologi Kedokteran Regeneratif',
    'Teknik Perumahsakitan',
    'Komputasi Biologi dan Bioinformatika ',
    'Rekayasa Sistem Saraf',
    'Robotika Medis',
    'Teknologi Kedokteran Onkologi',
    'Teknik Rehabilitasi'
]

k24s_biomed = {
    #Matkul nama lama : nama baru
    'Biologi Teknik dan Praktikum' : 'Biologi Dasar dan Praktikum',
    'Matematika Teknik 1' : 'Matematika Lanjut 1',
    'Statistik dan Probabilitas Biomedik' : 'Statistik dan Probabilitas',
    'Dasar Anatomi dan Fisiologi' : 'Anatomi dan Fisiologi Biomedik',
    'Etika Teknologi Biomedik' : 'Profesionalisme, Etika, dan Kewirausahaan Teknik Biomedik',
    'Matematika Teknik 2' : 'Matematika Lanjut 2',
    'Dasar Komputer dan Praktikum' : 'Praktikum Pemrograman C',
    'Sinyal dan Sistem' : 'Sinyal dan Sistem Biomedik',
    'Pengantar Instrumentasi Biomedik' : 'Manajemen Alat Kesehatan',
    'Standar Regulasi Teknik Biomedik' : 'Manajemen Alat Kesehatan',
    'Pemodelan Sistem Medis' : 'Pemodelan Sistem Biomedik',
    'Teori Medan Elektromagnetika' : 'Elektromagnetika dan Perancangan Divais RF Medis',
    'Divais Medis Sistem RF dan Microwave' : 'Elektromagnetika dan Perancangan Divais RF Medis',
    'Dasar Sistem Otomasi Biomedik' : 'Otomasi dan Kendali Sistem Biomedik',
    'Komputasi Numerik' : 'Komputasi Numerik Biomedik',
    'Kerja Praktek' : 'Magang',
    'Pra-Skripsi' : 'Seminar'
}

sks24_tekkom = {
    'Agama' : 2,
    'MPK Bahasa Inggris' : 2,
    'Kalkulus' : 4,
    'Fisika Listrik, MGO' : 3,
    'Praktikum Fisika Dasar' : 1,
    'Dasar Sistem Digital dan Praktikum' : 3,
    'Pemrograman Dasar dan Praktikum' : 3,
    'Berpikir Komputasional' : 2,
    'MPKT' : 6,
    'Aljabar Linier' : 4,
    'Fisika Mekanika dan Panas' : 3,
    'Praktikum Fisika Mekanika dan Panas' : 1,
    'Organisasi dan Arsitektur Komputer' : 3,
    'Algoritma dan Pemrograman dan Praktikum' : 3,
    'Pengantar Desain Teknik' : 2,
    'Dasar Rangkaian Elektronika' : 2,
    'Jaringan Komputer dan Praktikum' : 4,
    'Pemrograman Berorientasi Objek dan Praktik' : 3,
    'Perancangan Sistem Digital dan Praktikum' : 3,
    'Rangkaian Listrik' : 2,
    'Matematika Diskrit' : 3,
    'Statistika' : 3,
    'Aljabar Linier Lanjut' : 2,
    'Komputasi Numerik' : 3,
    'Desain & Manajemen Jaringan Komputer + P' : 3,
    'Matematika Lanjut' : 4,
    'Praktikum Rangkaian Listrik dan Elektronik' : 1,
    'Sistem Basis Data dan Praktikum' : 3,
    'Sistem Operasi dan Praktikum' : 3,
    'Sistem Embedded dan Praktikum' : 3,
    'Dasar Analitik Data' : 2,
    'Arsitektur Komputer Moderen' : 2,
    'Jaringan Telekomunikasi dan Praktikum' : 3,
    'Keamanan Jaringan Komputer dan Praktikum' : 3,
    'Probabilitas dan Proses Stokastik' : 3,
    'Rekayasa Perangkat Lunak' : 3,
    'Sistem Waktu Nyata dan IoT dan Praktikum' : 3,
    'Teori Sinyal dan Analisis Sistem' : 2,
    'Desain Proyek Teknik Komputer 1' : 2,
    'Kecerdasan Buatan' : 3,
    'Magang' : 2,
    'Kewirausahaan dalam Teknologi Informasi' : 2,
    'Pemrosesan Sinyal Multimedia' : 3,
    'Profesionalisme dan Etika dalam Teknologi Informasi' : 2,
    'Keberlanjutan, Kesehatan, dan Keselamatan Kerja' : 2,
    'Komputasi Awan' : 2,
    'Interaksi Manusia dan Komputer' : 2,
    'Desain Proyek Teknik Komputer 2' : 3,
    'Seminar' : 2,
    'Skripsi' : 4
}

sks24_elektro = {
    'Agama' :	2,
    'Bahasa Inggris' :	2,
    'Kalkulus' :	4,
    'Aljabar Linier' :	4,
    'Fisika Listrik, MGO' :	3,
    'Praktikum Fisika Dasar' :	1,
    'Pengantar Desain Teknik' :	2,
    'Berpikir Komputasional' :	2,
    'MPKT' :	6,
    'Fisika Mekanika dan Panas' :	3,
    'Rangkaian Listrik 1' :	3,
    'Dasar Sistem Digital dan Praktikum' :	3,
    'Matematika Lanjut 1' :	2,
    'Algoritma dan Pemrograman dan Praktikum' :	3,
    'Analisis Vektor dan Peubah Kompleks' :	2,
    'Rangkaian Listrik 2' :	2,
    'Praktikum Rangkaian Listrik' :	1,
    'Matematika Lanjut 2' :	4,
    'Matematika Diskrit' :	3,
    'Instrumentasi dan Pengukuran' :	2,
    'Praktikum Instrumentasi dan Pengukuran' :	1,
    'Dasar Analitik Data' :	2,
    'Devais Semikonduktor' :	2,
    'Material Listrik' :	2,
    'Statistika dan Probabilitas' :	4,
    'Elektromagnetika' :	3,
    'Rangkaian Elektronika 1' :	2,
    'Praktikum Rangkaian Elektronika' :	1,
    'Sinyal dan Sistem' :	3,
    'Teknik Tenaga Listrik' :	4,
    'Komputasi Numerik' :	2,
    'Sistem Embedded 1' :	3,
    'Praktikum Teknik Tenaga Listrik' :	1,
    'Sistem Telekomunikasi' :	4,
    'Praktikum Sistem Telekomunikasi' :	1,
    'Rangkaian Elektronika 2' :	2,
    'Teknik Kendali' : 4,
    'Praktikum Teknik Kendali' :	1,
    'Sistem Embedded 2 dan Praktikum' :	3,
    'Pemodelan dan Pembelajaran Mesin' :	3,
    'Inovasi dan Kewirausahaan' :	2,
    'Keberlanjutan, Kesehatan dan Keselamatan Kerja' :	2,
    'Desain Proyek Teknik Elektro 1' :	2,
    'Magang' :	2,
    'Desain Proyek Teknik Elektro 2' :	3,
    'Seminar' :	2,
    'Skripsi' :	4,
    'Rangkaian Mikroelektronika' : 3,
    'Devais Optoelektronik'	: 3,
    'Desain Rangkaian VLSI'	: 3,
    'Devais Nanoelektronika' : 2,
    'Devais Elektronika Lanjut'	: 3,
    'Desain Instrumentasi Elektronika' : 2,
    'Sistem Embedded Lanjut' : 3,
    'Elektronika Daya dan Praktikum' : 3,
    'Konversi Energi Listrik dan Energi Baru Terbarukan' : 3,
    'Sistem Tenaga Listrik dan Praktikum' : 3,
    'Jaringan Listrik Cerdas' : 2,
    'Teknik Tegangan dan Arus Tinggi dan Praktikum' : 3,
    'Distribusi dan Instalasi Listrik' : 3,
    'Proteksi Sistem Tenaga Listrik' : 2,
    'Komunikasi Digital' : 2,
    'Devais Sistem Telekomunikasi' : 3,
    'Antena dan Propagasi' : 3,
    'Pengolahan Sinyal dan Layanan Multimedia' : 3,
    'Komunikasi Optik' : 2,
    'Komunikasi Nirkabel dan Jaringan Konvergensi' : 2,
    'Desain Ekosistem TIK' : 2,
    'Sistem Radar' : 2,
    'Sistem Kendali Motor Listrik' : 3,
    'Sistem Kendali Prediktif dan Adaptif' : 3,
    'Sistem Kendaraan Otonomus' : 3,
    'Sistem Robotika' : 2,
    'Sistem Otomasi Industri' : 2,
    'Sistem Berbasis Pengetahuan' : 3,
    'Mekatronika' : 3,
    'Topik Khusus Tenaga Listrik 1' : 2,
    'Topik Khusus Telekomunikasi 1' : 2,
    'Topik Khusus Elektronika 1' : 2,
    'Topik Khusus Kendali 1' : 2,
    'Topik Khusus Tenaga Listrik 2' : 2,
    'Topik Khusus Telekomunikasi 2' : 2,
    'Topik Khusus Elektronika 2' : 2,
    'Topik Khusus Kendali 2' : 2
}

sks24_biomed = {
    'MPK Bahasa Inggris' :	2,
    'Agama' :	2,
    'Kalkulus' : 4,
    'Fisika Listrik, MGO' :	3,
    'Praktikum Fisika Listrik, MGO' :	1,
    'Kimia Dasar' :	2,
    'Biologi Dasar dan Praktikum' :	3,
    'Pengantar Desain Teknik' :	2,
    'Praktikum Kimia Dasar' :	1,
    'Dasar Sistem Digital dan Praktikum' : 3,
    'MPKT' : 6,
    'Aljabar Linier' : 4,
    'Fisika Mekanika dan Panas' : 3,
    'Praktikum Fisika Mekanika dan Panas' :	1,
    'Rangkaian Listrik' :	3,
    'Pengantar Informatika Medis' :	3,
    'Matematika Lanjut 1' :	3,
    'Statistik dan Probabilitas' : 3,
    'Elektronika Analog' : 3,
    'Praktikum Elektronika Analog' :	1,
    'Anatomi dan Fisiologi Biomedik' :	3,
    'Pengantar Teknologi Biomedik' :	3,
    'Berpikir Komputasional' :	2,
    'Menggambar Teknik' :	3,
    'Matematika Lanjut 2' :	3,
    'Praktikum Pemrograman C' :	1,
    'Sinyal dan Sistem Biomedik' :	2,
    'Manajemen Alat Kesehatan' :	3,
    'Pemodelan Sistem Biomedik' :	3,
    'Praktikum Pengantar Teknologi Biomedik' :	1,
    'Dasar Analitik Data' :	2,
    'Komputasi Numerik Biomedik' :	2,
    'Teknologi Pencitraan Medis' :	3,
    'Biomekanika' :	3,
    'Biomaterial' :	3,
    'Otomasi dan Kendali Sistem Biomedik' :	3,
    'Keberlanjutan, Kesehatan dan Keselamatan Kerja' :	2,
    'Sistem Embedded Biomedik dan Praktikum' :	3,
    'Profesionalisme, Etika, dan Kewirausahaan Teknik Biomedik' :	2,
    'Elektromagnetika dan Perancangan Divais RF Medis' :	4,
    'Pengolahan Sinyal Medis' :	3,
    'Perancangan Sensor Biomedik' :	3,
    'Desain Proyek Teknik Biomedik 1' :	2,
    'Magang' :	2,
    'Desain Proyek Teknik Biomedik 2' :	3,
    'Seminar' :	2,
    'Skripsi' :	4,
}

# !!jadikan kurikulum input CSV